#!/usr/bin/env python3
"""star_history.py - self-made Star History chart for HANT PORT.

Fetches stargazer timestamps from the GitHub REST API and renders a
hand-written SVG line chart. Zero third-party services, zero pip
dependencies - standard library only.

Usage:
    python tools/star_history.py --repo CLXV11/Hant-Port --out docs/star-history.svg
    python tools/star_history.py --demo            # render with simulated data

Regenerate any time, or let .github/workflows/star-history.yml do it weekly.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone


def fetch_star_events(owner, repo_name, token):
    """Return a sorted list of starred_at datetimes (UTC)."""
    events = []
    page = 1
    while True:
        url = ("https://api.github.com/repos/" + owner + "/" + repo_name +
               "/stargazers?per_page=100&page=" + str(page))
        headers = {
            "Accept": "application/vnd.github.star+json",
            "User-Agent": "hant-port-star-history",
        }
        if token:
            headers["Authorization"] = "Bearer " + token
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                batch = json.loads(resp.read().decode())
        except urllib.error.HTTPError as exc:
            if exc.code in (401, 403):
                sys.exit("error: GitHub API rejected the request - set GITHUB_TOKEN "
                         "( Actions provides it automatically; locally: --token or env )")
            raise
        if not batch:
            break
        for item in batch:
            ts = item.get("starred_at")
            if ts:
                events.append(datetime.fromisoformat(ts.replace("Z", "+00:00")))
        if len(batch) < 100:
            break
        page += 1
    return sorted(events)


W, H = 800, 320
PAD_L, PAD_R, PAD_T, PAD_B = 56, 24, 24, 44
PLOT_W = W - PAD_L - PAD_R
PLOT_H = H - PAD_T - PAD_B

SVG_HEADER = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" role="img" aria-label="Star history of {repo_full}">
<defs>
  <linearGradient id="lineGrad" x1="0" y1="0" x2="1" y2="0">
    <stop offset="0%" stop-color="#22d3ee"/>
    <stop offset="100%" stop-color="#4ade80"/>
  </linearGradient>
  <linearGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0%" stop-color="#22d3ee" stop-opacity="0.30"/>
    <stop offset="100%" stop-color="#4ade80" stop-opacity="0.02"/>
  </linearGradient>
</defs>
<style>
  text {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }}
  .tick {{ font-size: 11px; fill: #59636e; }}
  .caption {{ font-size: 10px; fill: #8b949e; }}
  .grid {{ stroke: #d8dee4; stroke-width: 1; }}
  .axis {{ stroke: #8b949e; stroke-width: 1.2; }}
  .line {{ fill: none; stroke: url(#lineGrad); stroke-width: 2.5; stroke-linecap: round; }}
  .area {{ fill: url(#areaGrad); }}
  .dot {{ fill: #ffffff; stroke: url(#lineGrad); stroke-width: 2; }}
  @media (prefers-color-scheme: dark) {{
    .tick {{ fill: #9198a1; }}
    .grid {{ stroke: #21262d; }}
    .axis {{ stroke: #484f58; }}
    .dot {{ fill: #0d1117; }}
  }}
</style>"""

EMPTY_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" role="img" aria-label="Star history of {repo_full}">
<defs><linearGradient id="lineGrad" x1="0" y1="0" x2="1" y2="0">
  <stop offset="0%" stop-color="#22d3ee"/><stop offset="100%" stop-color="#4ade80"/>
</linearGradient></defs>
<style>
  .msg {{ font: 600 20px ui-monospace, Menlo, monospace; fill: #59636e; }}
  .sub {{ font: 12px ui-monospace, Menlo, monospace; fill: #8b949e; }}
  .star {{ fill: url(#lineGrad); }}
  @media (prefers-color-scheme: dark) {{ .msg {{ fill: #9198a1; }} .sub {{ fill: #6e7681; }} }}
</style>
<text class="msg" x="{W2}" y="{H2m}" text-anchor="middle">No stars yet - be the first!</text>
<text class="sub" x="{W2}" y="{H2p}" text-anchor="middle">self-generated by tools/star_history.py</text>
<text class="star" x="{W2}" y="{H2s}" text-anchor="middle" font-size="34">&#9733;</text>
</svg>"""


def render_svg(events, repo_full):
    if not events:
        return EMPTY_SVG.format(W=W, H=H, W2=W // 2, H2m=H // 2 - 10,
                                H2p=H // 2 + 18, H2s=H // 2 + 62,
                                repo_full=repo_full)

    t0, t1 = events[0], events[-1]
    if t1 - t0 < timedelta(days=2):
        t0, t1 = t0 - timedelta(days=1), t1 + timedelta(days=1)
    max_stars = len(events)

    def X(dt):
        return PAD_L + PLOT_W * ((dt - t0).total_seconds() / (t1 - t0).total_seconds())

    def Y(n):
        return PAD_T + PLOT_H * (1 - n / max_stars)

    parts = [SVG_HEADER.format(W=W, H=H, repo_full=repo_full)]
    for i in range(5):
        n = max_stars * i / 4
        y = Y(n)
        parts.append('<line class="grid" x1="%d" y1="%.1f" x2="%d" y2="%.1f"/>' % (PAD_L, y, W - PAD_R, y))
        parts.append('<text class="tick" x="%d" y="%.1f" text-anchor="end">%d</text>' % (PAD_L - 8, y + 4, round(n)))
    for i in range(5):
        dt = t0 + (t1 - t0) * i / 4
        x = X(dt)
        parts.append('<text class="tick" x="%.1f" y="%d" text-anchor="middle">%s</text>'
                     % (x, H - PAD_B + 20, dt.strftime("%b %d")))
    parts.append('<line class="axis" x1="%d" y1="%d" x2="%d" y2="%d"/>' % (PAD_L, PAD_T, PAD_L, H - PAD_B))
    parts.append('<line class="axis" x1="%d" y1="%d" x2="%d" y2="%d"/>' % (PAD_L, H - PAD_B, W - PAD_R, H - PAD_B))

    pts = [(X(e), Y(i + 1)) for i, e in enumerate(events)]

    if len(pts) == 1:
        parts.append('<circle cx="%.1f" cy="%.1f" r="5" fill="url(#lineGrad)"/>' % pts[0])
    else:
        area = " ".join("%.1f,%.1f" % (x, y) for x, y in pts)
        parts.append('<polygon class="area" points="%d,%d %s %.1f,%d"/>'
                     % (PAD_L, H - PAD_B, area, pts[-1][0], H - PAD_B))
        d = "M %.1f %.1f " % pts[0]
        for i in range(len(pts) - 1):
            p0 = pts[max(i - 1, 0)]
            p1, p2 = pts[i], pts[i + 1]
            p3 = pts[min(i + 2, len(pts) - 1)]
            c1x = p1[0] + (p2[0] - p0[0]) / 6
            c1y = p1[1] + (p2[1] - p0[1]) / 6
            c2x = p2[0] - (p3[0] - p1[0]) / 6
            c2y = p2[1] - (p3[1] - p1[1]) / 6
            d += "C %.1f %.1f %.1f %.1f %.1f %.1f " % (c1x, c1y, c2x, c2y, p2[0], p2[1])
        parts.append('<path class="line" d="%s"/>' % d)
        for x, y in pts:
            parts.append('<circle class="dot" cx="%.1f" cy="%.1f" r="3.5"/>' % (x, y))

    parts.append('<text class="caption" x="%d" y="%d" text-anchor="end">'
                 'self-generated by tools/star_history.py</text>' % (W - PAD_R, H - 6))
    parts.append("</svg>")
    return "\n".join(parts)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", ""))
    ap.add_argument("--out", default="docs/star-history.svg")
    ap.add_argument("--token", default=os.environ.get("GITHUB_TOKEN", ""))
    ap.add_argument("--demo", action="store_true", help="render simulated data")
    args = ap.parse_args(argv)

    if args.demo:
        now = datetime.now(timezone.utc)
        events = sorted(now - timedelta(days=30 * (30 - i) / 29) for i in range(31))
    else:
        if not args.repo or "/" not in args.repo:
            sys.exit("error: pass --repo OWNER/NAME or set GITHUB_REPOSITORY")
        owner, name = args.repo.split("/", 1)
        events = fetch_star_events(owner, name, args.token or None)

    svg = render_svg(events, args.repo or "demo")
    import pathlib as _pl
    out = _pl.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(svg, encoding="utf-8")
    print("wrote %s (%d star events)" % (out, len(events)))


if __name__ == "__main__":
    main()
